### ISSUE TITLE
2 Bugs Detected

### ISSUE THREAD

**Issue by chunwtup** [fafa17/COMP324#22]
Account:
Inventory head
user: IYF 
password: 123456 

Small Boat Team A head
user: FKC
password: 123456 
1.    In "Report" Section
   Number of owned item & Number of current item  is not correctly display in "Report" Section
   First, login to IYF
   For example, 
   There are 4 Helmet A in location "Inventory" when view on "Manage item" section
   However,
   in "Report" Section, there is only 1 Helmet A.
2.   In Borrow request and Transfer request Section
   The serial number is different in Borrow request and Transfer request.
   For example, 
   i sent a borrow request with 2 Helmet A
   Then, i received the borrow request and select 2 Helmet A with serial number HMA001 and HMA005 
   Then, i go back and received a transfer request, The serial number of Helmet A is not HMA001 and HMA005.

I hope you understand, lol
Eric will send you some more bugs tmr.

**Comment by chris-cyliu** [comment]
fix bug 1 in 02f1730c6778137a5de6f83345170151e21220a3

**Comment by chris-cyliu** [comment]
fix bug 2 in dd51766127cd96c7d2b6e2d2b83ef41d451a0371
