### ISSUE TITLE
"Inventory Check" layout 

### ISSUE THREAD

**Issue by chris-cyliu** [fafa17/COMP324#3]
For "InventoryCheck.html"
We have "Location" to represent each Division, subunit and individual 
It is a little bit confuse to use "Division" may be just use "Location"

Also "Equipment Type: " is a kind of filtering of item. I think we can take it out first. We can filter it by using DataTable function later on. Please take it out

Also there are some non-relatived items in the left menu , such as "Related Web Sites" please take it out

**Comment by Julian-IP0** [comment]
Done
